export const ENV = {
  GEMINI_API_KEY: process.env.EXPO_PUBLIC_GEMINI_API_KEY || "",
  GEMINI_API_KEY_FALLBACK: process.env.EXPO_PUBLIC_GEMINI_API_KEY_FALLBACK || "",
  OPENAI_API_KEY: process.env.EXPO_PUBLIC_OPENAI_API_KEY || "",
  GOOGLE_MAPS_API_KEY: process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY || "",
  RESEND_API_KEY: process.env.EXPO_PUBLIC_RESEND_API_KEY || "",
};
